apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: lifytp
data:
  NODE_ENV: "production"
  PORT: "4100"
  HOST: "0.0.0.0"
  JWT_ACCESS_EXPIRES: "15m"
  JWT_REFRESH_EXPIRES: "7d"
  CORS_ORIGIN: "*"
