apiVersion: v1
kind: ConfigMap
metadata:
  name: events-config
  namespace: lifytp
data:
  NODE_ENV: "production"
  PORT: "4101"
  HOST: "0.0.0.0"
  CORS_ORIGIN: "*"
  MINIO_ENDPOINT: "minio-service"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: "lifytp-uploads"
