apiVersion: v1
kind: ConfigMap
metadata:
  name: messages-config
  namespace: lifytp
data:
  NODE_ENV: "production"
  PORT: "4102"
  HOST: "0.0.0.0"
  CORS_ORIGIN: "*"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
