apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: lifytp
  labels:
    app: events-service
spec:
  type: ClusterIP
  ports:
  - port: 4101
    targetPort: 4101
    protocol: TCP
    name: http
  selector:
    app: events-service
